"""add indexes for frequently queried columns

Revision ID: 64efd99ef4cc
Revises: 58623114c17e
Create Date: 2026-03-28 12:49:17.517454+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64efd99ef4cc"
down_revision: Union[str, None] = "58623114c17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_ap_delivery_queue_status"), "ap_delivery_queue", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ap_delivery_queue_target_inbox"),
        "ap_delivery_queue",
        ["target_inbox"],
        unique=False,
    )
    op.create_index(op.f("ix_boosts_note_uri"), "boosts", ["note_uri"], unique=False)
    op.create_index(op.f("ix_followers_status"), "followers", ["status"], unique=False)
    op.create_index(op.f("ix_following_status"), "following", ["status"], unique=False)
    op.create_index(op.f("ix_likes_actor_uri"), "likes", ["actor_uri"], unique=False)
    op.create_index(op.f("ix_likes_note_uri"), "likes", ["note_uri"], unique=False)
    op.create_index(op.f("ix_notifications_read"), "notifications", ["read"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_read"), table_name="notifications")
    op.drop_index(op.f("ix_likes_note_uri"), table_name="likes")
    op.drop_index(op.f("ix_likes_actor_uri"), table_name="likes")
    op.drop_index(op.f("ix_following_status"), table_name="following")
    op.drop_index(op.f("ix_followers_status"), table_name="followers")
    op.drop_index(op.f("ix_boosts_note_uri"), table_name="boosts")
    op.drop_index(op.f("ix_ap_delivery_queue_target_inbox"), table_name="ap_delivery_queue")
    op.drop_index(op.f("ix_ap_delivery_queue_status"), table_name="ap_delivery_queue")
    # ### end Alembic commands ###
