"""add bio and header image to remote actors, add content to notifications

Revision ID: d630cad55ef3
Revises: a87933dc7e06
Create Date: 2026-03-21 02:51:18.287373+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d630cad55ef3"
down_revision: str | None = "a87933dc7e06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("content", sa.Text(), nullable=True))
    op.add_column("remote_actors", sa.Column("bio", sa.Text(), nullable=True))
    op.add_column("remote_actors", sa.Column("header_image_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("remote_actors", "header_image_url")
    op.drop_column("remote_actors", "bio")
    op.drop_column("notifications", "content")
    # ### end Alembic commands ###
