"""Notification model for tracking likes, boosts, follows, and replies.

Notifications are created when remote actors interact with the local
actor's content or follow the local actor.
"""

from __future__ import annotations

from sqlalchemy import Boolean, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import UUIDModel


class Notification(UUIDModel):
    """A notification generated by remote actor interactions.

    Attributes:
        id: UUID primary key.
        created_at: Timestamp when the notification was created.
        type: The notification type — one of "like", "boost", "follow", "reply".
        actor_uri: The AP URI of the actor who triggered the notification.
        actor_name: Display name of the triggering actor, if known.
        object_uri: The AP URI of the object involved, if applicable.
        content: Sanitised HTML content of the object, for reply notifications.
        read: Whether the notification has been read by the admin.
    """

    __tablename__ = "notifications"

    type: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    actor_uri: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    actor_name: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        default=None,
    )
    object_uri: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        default=None,
    )
    content: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        default=None,
    )
    read: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        index=True,
    )

    def __repr__(self) -> str:
        """Return a developer-friendly string representation."""
        return (
            f"<Notification(id={self.id!r}, type={self.type!r}, "
            f"actor_uri={self.actor_uri!r}, read={self.read!r})>"
        )
